# Oh My Zsh
#
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-completions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true

# Other than Oh My Zsh
#
setopt autocd
setopt autopushd

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export EDITOR=vim
export PATH=${KREW_ROOT:-$HOME/.krew}/bin:$PATH
export PATH=${HOME}/.local/bin:$PATH

export NVM_DIR=/usr/local/share/nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"

alias k=kubectl
alias tf-state-cleanup='terraform state list | cut -f 1 -d "[" | xargs -L 1 terraform state rm'

eval "$(jump shell zsh)"

if [ -f "$HOME/.zfunc/_rustup" ]; then
  FPATH=$HOME/.zfunc:$FPATH
fi

autoload -Uz +X compinit && compinit -u
autoload -Uz +X bashcompinit && bashcompinit

source /etc/bash_completion.d/azure-cli

source <(kubectl completion zsh)
complete -o default -F __start_kubectl k

source <(helm completion zsh)

complete -o nospace -C /usr/local/bin/terraform terraform

if [ -f "$HOME/.cargo/env" ]; then
  source $HOME/.cargo/env
fi

command -v flux >/dev/null && . <(flux completion zsh) && compdef _flux flux

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

function ghenv() {
  eval $(op signin)
  export GITHUB_TOKEN=$(op read op://Personal/GitHub_PAT_CLI_Interactive/password)
  export GITHUB_USER=$(op read  op://Personal/GitHub_PAT_CLI_Interactive/notesPlain)
}

function azenv() {
  eval $(op signin)
  export ARM_CLIENT_ID=$(op read op://Personal/Azure-SP-Work-Hybrid-Subscription-Contributor/client_id)
  export ARM_CLIENT_SECRET=$(op read op://Personal/Azure-SP-Work-Hybrid-Subscription-Contributor/client_secret)
  export ARM_SUBSCRIPTION_ID=$(op read op://Personal/Azure-SP-Work-Hybrid-Subscription-Contributor/subscription_id)
  export ARM_TENANT_ID=$(op read  op://Personal/Azure-SP-Work-Hybrid-Subscription-Contributor/tenant_id)
}

# For WSL
#
# export PATH=$PATH:'/mnt/c/Users/tomakabe/AppData/Local/Programs/Microsoft VS Code/bin'
#
# Workaround https://github.com/docker/for-win/issues/6391
# alias kubectl="/usr/bin/kubectl"
