alias arm="exec arch -arch arm64e /bin/zsh --login"
alias x64="exec arch -arch x86_64 /bin/zsh --login"

setopt autocd
setopt autopushd

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export DOCKER_BUILDKIT=1
export EDITOR=vim
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

ARCH=$(uname -m)
PROMPT="${ARCH} %# "

alias ll="ls -alh"
alias phist='history | peco'
alias k=kubectl
alias tf-state-cleanup='terraform state list | cut -f 1 -d "[" | xargs -L 1 terraform state rm'

eval "$(jump shell zsh)"

if [ -e /usr/local/share/zsh-completions ]; then
    fpath=(/usr/local/share/zsh-completions $fpath)
fi

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

if [ -f "$HOME/.zfunc/_rustup" ]; then
  FPATH=$HOME/.zfunc:$FPATH
fi

autoload -Uz +X compinit && compinit -u
autoload -Uz +X bashcompinit && bashcompinit

if [ -f "$HOME/.zsh/completions/az.completion" ]; then
  source $HOME/.zsh/completions/az.completion
fi

source <(kubectl completion zsh)
complete -o default -F __start_kubectl k

source <(helm completion zsh)

if [ "$ARCH" = "arm64e" ]; then
complete -o nospace -C /opt/homebrew/bin/terraform terraform
else
complete -o nospace -C /usr/local/bin/terraform terraform
fi

. "$HOME/.cargo/env"

command -v flux >/dev/null && . <(flux completion zsh) && compdef _flux flux

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
